### PR TITLE
OAPS-188: Use checksum to access each application forms

### PR DESCRIPTION
**Pull request by monishdeb**

### CODE REVIEW

**Comment by seamuslee001** [comment]
Hi @monishdeb 

The logic of this is right, just thinking through the UX of this. If someone saves a draft we then release this then they can't use the link in their email. My thinking is that perhaps what we should do is that if we don't have a checksum or if the checksum is no longer valid trigger a new draft email with a status message saying check your email for an updated draft link or something what you think?

**Comment by monishdeb** [comment]
>  if we don't have a checksum or if the checksum is no longer valid trigger a new draft email with a status message saying check your email for an updated draft link or something what you think? 


@seamuslee001  Yes I had the same thought in my mind so I have resolved the later part where the checksum generated has no life limit as I used ```inf``` hash. See [here](https://github.com/civicrm/civicrm-core/blob/master/CRM/Contact/BAO/Contact/Utils.php#L224) in core. Now the problem arise for providers whose application is in draft mode. They have the old draft link without CS in the url which is no longer valid. For those contact we need to write a short script or need to hack code temporarily (by commenting out the validation message in prod code) to send a new draft to those contacts. So that next time they will be able to open the application with CS as one the url argument. What do you think ?

**Comment by seamuslee001** [comment]
@monishdeb i think the email blast out will solve things for us. Note i think we need to fix this https://github.com/JMAConsulting/biz.jmaconsulting.oapproviderlistapp/blob/master/CRM/Oapproviderlistapp/Form/ManageApplication.php#L160 and https://github.com/JMAConsulting/biz.jmaconsulting.oapproviderlistapp/blob/master/CRM/Oapproviderlistapp/Page/Draft.php#L13

**Comment by seamuslee001** [comment]
also this looks like it needs the fix applied https://github.com/JMAConsulting/biz.jmaconsulting.oapproviderlistapp/blob/master/CRM/Oapproviderlistapp/Page/Draft.php#L13

**Comment by monishdeb** [comment]
Thanks @seamuslee001 for making those additional fixes and adding translation for email textss. Merging this PR as we have tested this staging.

**Pull request merged**
