### PR TITLE
OAPS-60 Fix trademark display on french side and also ensure that registered mark is useed consistantly

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Review by JoeMurray — COMMENTED** [review]
This one needs testing on particular browser versions IIRC. Please refer to JIRA where that was noted in old tickets. IIRC it was IE that was causing issues. Let's post images from this working in different browsers here as QA evidence.

**Comment by seamuslee001** [comment]
@JoeMurray 

Search Form - English - Chrome
eng-search-chrome

Search Form - English - Firefox
eng-search-firefox

Search Form - English - Edge
eng-search-edge

Search Form - English - IE
eng-search-ie

Search Form - French - Chrome
fr-search-chrome

Search Form - French - Firefox
fr-search-firefox

Search Form - French - Edge
fr-search-edge

Search Form - French - IE
fr-search-ie

Professional Tab - English - Chrome
eng-professional-chrome

Professional Tab - English - Firefox
eng-professional-firefox

Professional Tab - English - Edge
eng-professional-edge

Professional Tab - English - IE
eng-professional-ie

Professional Tab - French - Chrome
fr-profressional-chrome

Professional Tab - French - FireFox
fr-profressional-firefox

Professional Tab - French - Edge
fr-profressional-edge

Professional Tab - French - IE
fr-profressional-ie

**Comment by seamuslee001** [comment]
@JoeMurray the reason why this is more 'portable' between browsers is that i'm not actually using the unicode format to generate it, Its using the string  MC contained within a span so that then I use css to style it as if it was superscript

**Comment by JoeMurray** [comment]
Thanks for all the images. I think I only needed the french ones.

Okay, so we are not trying to use the symbol for _marque de commerce_  (MC) or for _marque déposée_ (MD) but are merely using superscripts. In this context, I would recommend reviewing what the original JIRA request was as we are putting (R) in English but MC in French. Normally (R) is equivalent to MD, and TM is equivalent to MC. If they want MC fine, but I suspect they might have asked for MD.

**Comment by seamuslee001** [comment]
@JoeMurray ah my bad that is my fault got them confused will switch to MD

**Comment by seamuslee001** [comment]
@JoeMurray i have now fixed it to use MD not MC that was just me getting confused

**Comment by seamuslee001** [comment]
Jennifer has confirmed this is good merging

**Pull request merged**
